import Foundation
import SwiftData

@Model
final class Turn {
    /// Unique identifier from the JSONL line — used for deduplication.
    @Attribute(.unique) var uuid: String

    var session: Session?

    var timestamp: Date

    /// Model identifier, e.g. "claude-opus-4-6", "claude-haiku-4-5-20251001", "o3".
    var model: String

    /// Provider: "claude" or "openai".
    var provider: String

    // MARK: - Claude token fields

    /// Non-cached input tokens.
    var inputTokens: Int = 0

    /// Output tokens generated by the model.
    var outputTokens: Int = 0

    /// Tokens written to cache.
    var cacheCreationTokens: Int = 0

    /// Tokens read from an existing cache.
    var cacheReadTokens: Int = 0

    /// Ephemeral 5-minute TTL cache creation tokens.
    var cacheCreation5mTokens: Int = 0

    /// Ephemeral 1-hour TTL cache creation tokens.
    var cacheCreation1hTokens: Int = 0

    // MARK: - OpenAI token fields

    /// Internal reasoning tokens (o3, o4-mini).
    var reasoningTokens: Int = 0

    /// Cached prompt tokens from OpenAI automatic caching.
    var cachedPromptTokens: Int = 0

    // MARK: - Metadata

    /// Whether this turn was produced by a subagent.
    var isSubagent: Bool = false

    /// Subagent type from meta.json, e.g. "Explore", "Plan".
    var subagentType: String?

    /// Estimated cost in USD.
    var estimatedCostUSD: Double = 0.0

    init(
        uuid: String,
        timestamp: Date,
        model: String,
        provider: String
    ) {
        self.uuid = uuid
        self.timestamp = timestamp
        self.model = model
        self.provider = provider
    }

    // MARK: - Computed properties

    /// Total input tokens including all cache types.
    /// For Claude: input_tokens + cache_creation_input_tokens + cache_read_input_tokens
    /// For OpenAI: inputTokens includes prompt_tokens (which contains cached)
    var totalInputTokens: Int {
        inputTokens + cacheCreationTokens + cacheReadTokens
    }

    /// Grand total of all tokens for this turn.
    var totalTokens: Int {
        totalInputTokens + outputTokens
    }

    /// Tokens that would have been full-price input but were served from cache.
    var tokensSavedByCache: Int {
        cacheReadTokens
    }
}
